# Generated by Django 5.2.5 on 2025-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodmast',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prodmast',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
